services:
  - type: web
    name: pokka-arcade
    env: static
    buildCommand: |
      cd pokka-snakes-gl/client && npm install && npm run build && cd ../.. && cp -r assets/* .
    staticPublishPath: .
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
