services:
  - type: web
    name: pokka-arcade
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: Content-Type
        value: text/javascript
      - path: /assets/*
        name: Content-Type
        value: text/javascript
      - path: /*.js
        name: Content-Type
        value: text/javascript
      - path: /*.mjs
        name: Content-Type
        value: text/javascript
      - path: /*.jsx
        name: Content-Type
        value: text/javascript
      - path: /*.ts
        name: Content-Type
        value: text/javascript
      - path: /*.tsx
        name: Content-Type
        value: text/javascript
    envVars:
      - key: NODE_VERSION
        value: 20.11.5
      - key: NPM_VERSION
        value: 10.2.4
      - key: VITE_FIREBASE_API_KEY
        sync: false
      - key: VITE_FIREBASE_AUTH_DOMAIN
        sync: false
      - key: VITE_FIREBASE_PROJECT_ID
        sync: false
      - key: VITE_FIREBASE_STORAGE_BUCKET
        sync: false
      - key: VITE_FIREBASE_MESSAGING_SENDER_ID
        sync: false
      - key: VITE_FIREBASE_APP_ID
        sync: false
      - key: VITE_FIREBASE_DATABASE_URL
        sync: false
      - key: VITE_CRYPTOCOMPARE_API_KEY
        sync: false
      - key: VITE_WALLETCONNECT_PROJECT_ID
        sync: false

  # Legacy games support
  - type: web
    name: pokka-man-legacy
    env: static
    buildCommand: echo "Serving static files"
    staticPublishPath: ./pokka-man
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  - type: web
    name: pokka-falling-blocks-legacy
    env: static
    buildCommand: echo "Serving static files"
    staticPublishPath: ./pokka-falling-blocks
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  - type: web
    name: pokka-snakes-legacy
    env: static
    buildCommand: echo "Serving static files"
    staticPublishPath: ./pokka-snakes-gl/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
