services:
  - type: web
    name: pokka-arcade
    env: static
    buildCommand: |
      cd pokka-snakes-gl/client && npm install && npm run build && cd ../.. && \
      mkdir -p public && \
      cp -r pokka-snakes-gl/dist/* public/ && \
      cp -r pokka-man public/ && \
      cp -r pokka-falling-blocks public/ && \
      cp -r assets public/ && \
      cp index.html public/
    staticPublishPath: public
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
