services:
  - type: web
    name: dev-pokka
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*.js
        name: Content-Type
        value: application/javascript
      - path: /*.mjs
        name: Content-Type
        value: application/javascript
      - path: /*.css
        name: Content-Type
        value: text/css
      - path: /*.png
        name: Content-Type
        value: image/png
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: https://dev-pokka.onrender.com
      - key: VITE_FIREBASE_API_KEY
        sync: false
      - key: VITE_FIREBASE_AUTH_DOMAIN
        sync: false
      - key: VITE_FIREBASE_PROJECT_ID
        sync: false
      - key: VITE_FIREBASE_STORAGE_BUCKET
        sync: false
      - key: VITE_FIREBASE_MESSAGING_SENDER_ID
        sync: false
      - key: VITE_FIREBASE_APP_ID
        sync: false
      - key: VITE_FIREBASE_DATABASE_URL
        sync: false
      - key: VITE_CRYPTOCOMPARE_API_KEY
        sync: false
      - key: VITE_WALLETCONNECT_PROJECT_ID
        sync: false

  # Legacy games support
  - type: web
    name: dev-pokka-man-legacy
    env: static
    buildCommand: echo "Serving static files"
    staticPublishPath: ./pokka-man
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  - type: web
    name: dev-pokka-falling-blocks-legacy
    env: static
    buildCommand: echo "Serving static files"
    staticPublishPath: ./pokka-falling-blocks
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  - type: web
    name: dev-pokka-snakes-legacy
    env: static
    buildCommand: echo "Serving static files"
    staticPublishPath: ./pokka-snakes-gl/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
